package net.javaguides.cms.entity;

/**
 * Represents a security role within the system, used to grant and control access to various features and functionalities.
 * This entity is stored in the 'role' table in the database. Each role has a unique identifier and a name.
 *
 * <p>The {@link Role} entity includes the following properties:
 * <ul>
 *   <li>id: The unique identifier for the role, automatically generated by the database.
 *   <li>name: The name of the role, which describes the role's purpose or associated permissions.
 * </ul>
 *
 * <p>Usage of this entity includes, but is not limited to, assigning roles to users to control access permissions
 * across the system. Roles can be used in conjunction with Spring Security to secure endpoints based on user roles.
 *
 * @author Annotated with Lombok's {@link Getter}, {@link Setter}, {@link NoArgsConstructor}, and {@link AllArgsConstructor}.
 * @see jakarta.persistence.Entity
 */
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "role")
public class Role {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  private String name;
}
